In [1]:
import pandas as pd

## Importing the main database consisting of the earthquake data
Concerned Attributes
```
   1. Latitude
   2. Longitude
   3. Magnitude
   4. Depth 

```

In [2]:
df=pd.read_csv('project/earthquake_database.csv')

In [3]:
df.head()

,Unnamed: 0,Date,Time,Latitude,Longitude,Type,Depth,Depth Error,Depth Seismic Stations,Magnitude,...,Magnitude Seismic Stations,Azimuthal Gap,Horizontal Distance,Horizontal Error,Root Mean Square,ID,Source,Location Source,Magnitude Source,Status
0,0,01/02/1965,13:44:18,19.246,145.616,Earthquake,131.6,NaN,NaN,6.0,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860706,ISCGEM,ISCGEM,ISCGEM,Automatic
1,1,01/04/1965,11:29:49,1.863,127.352,Earthquake,80.0,NaN,NaN,5.8,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860737,ISCGEM,ISCGEM,ISCGEM,Automatic
2,2,01/05/1965,18:05:58,-20.579,-173.972,Earthquake,20.0,NaN,NaN,6.2,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860762,ISCGEM,ISCGEM,ISCGEM,Automatic
3,3,01/08/1965,18:49:43,-59.076,-23.557,Earthquake,15.0,NaN,NaN,5.8,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860856,ISCGEM,ISCGEM,ISCGEM,Automatic
4,4,01/09/1965,13:32:50,11.938,126.427,Earthquake,15.0,NaN,NaN,5.8,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860890,ISCGEM,ISCGEM,ISCGEM,Automatic

## Plotting all the earthquakes

In [6]:
#filetring it 
import folium
import pandas as pd

map = folium.Map(location=[38.58, -99.09], zoom_start=6, tiles="Mapbox Bright")
fgd=folium.FeatureGroup(name='Earthquakes')

data1=df
lat=list(data1['Latitude'])
lon=list(data1['Longitude'])
depth=list(data1['Depth'])
elev=list(data1['Magnitude'])

def color_producer(elevation):
    if elevation >6.00:
        return 'red'
    elif 5.8 <= elevation < 6.00:
        return 'blue'
    else:
        return 'white'

def radius_producer(dep):
    if dep > 60:
        return 8
    elif 50 <= dep <60:
        return 3
    else:
        return 2
    
for lt, ln, el,dep in zip(lat, lon, elev,depth):
    fgd.add_child(folium.CircleMarker(location=[lt, ln], radius = radius_producer(dep), popup=str(el),
    fill_color=color_producer(el), fill=True,  color = 'grey', fill_opacity=0.7))
    
map.add_child(fgd)
map.add_child(folium.LayerControl())
map.save('project/map_earthquakes_world.html')

### Since dataset is really big, we have to divide the parts of the world in components and study each part. Let's take the Northen- East Zone 'Kazakistan to Japan'

In [7]:
# Area for Northen- East Zone

latitude1,latitude2=51.578939,-0.941773
longitude1,longitude2=58.022448,148.549792

In [8]:
#Longitude Filter
d_new=df.loc[(df['Longitude']>=longitude1) & (df['Longitude']<=longitude2)]
d_new.head()

,Unnamed: 0,Date,Time,Latitude,Longitude,Type,Depth,Depth Error,Depth Seismic Stations,Magnitude,...,Magnitude Seismic Stations,Azimuthal Gap,Horizontal Distance,Horizontal Error,Root Mean Square,ID,Source,Location Source,Magnitude Source,Status
0,0,01/02/1965,13:44:18,19.246,145.616,Earthquake,131.6,NaN,NaN,6.0,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860706,ISCGEM,ISCGEM,ISCGEM,Automatic
1,1,01/04/1965,11:29:49,1.863,127.352,Earthquake,80.0,NaN,NaN,5.8,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860737,ISCGEM,ISCGEM,ISCGEM,Automatic
4,4,01/09/1965,13:32:50,11.938,126.427,Earthquake,15.0,NaN,NaN,5.8,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860890,ISCGEM,ISCGEM,ISCGEM,Automatic
6,6,01/12/1965,13:32:25,27.357,87.867,Earthquake,20.0,NaN,NaN,5.9,...,NaN,NaN,NaN,NaN,NaN,ISCGEM861007,ISCGEM,ISCGEM,ISCGEM,Automatic
10,10,01/17/1965,20:57:41,-6.807,108.988,Earthquake,227.9,NaN,NaN,5.9,...,NaN,NaN,NaN,NaN,NaN,ISCGEM861155,ISCGEM,ISCGEM,ISCGEM,Automatic

In [9]:
#latitude Filter
d_new=d_new.loc[(d_new['Latitude']<=latitude1) & (d_new['Latitude']>=latitude2)]
d_new.head()

,Unnamed: 0,Date,Time,Latitude,Longitude,Type,Depth,Depth Error,Depth Seismic Stations,Magnitude,...,Magnitude Seismic Stations,Azimuthal Gap,Horizontal Distance,Horizontal Error,Root Mean Square,ID,Source,Location Source,Magnitude Source,Status
0,0,01/02/1965,13:44:18,19.246,145.616,Earthquake,131.6,NaN,NaN,6.0,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860706,ISCGEM,ISCGEM,ISCGEM,Automatic
1,1,01/04/1965,11:29:49,1.863,127.352,Earthquake,80.0,NaN,NaN,5.8,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860737,ISCGEM,ISCGEM,ISCGEM,Automatic
4,4,01/09/1965,13:32:50,11.938,126.427,Earthquake,15.0,NaN,NaN,5.8,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860890,ISCGEM,ISCGEM,ISCGEM,Automatic
6,6,01/12/1965,13:32:25,27.357,87.867,Earthquake,20.0,NaN,NaN,5.9,...,NaN,NaN,NaN,NaN,NaN,ISCGEM861007,ISCGEM,ISCGEM,ISCGEM,Automatic
14,14,02/02/1965,15:56:51,37.523,73.251,Earthquake,15.0,NaN,NaN,6.0,...,NaN,NaN,NaN,NaN,NaN,ISCGEM859164,ISCGEM,ISCGEM,ISCGEM,Automatic

In [10]:
len(d_new)

5969

In [12]:
d_new.to_csv('project/earthquake_japan.csv')

## Importing Dams Database
Concerned Attributes
```
    1. Longitude
    2. Latitude
    3. Country
    4. Name
    5. Year Completed
```

In [13]:
df=pd.read_csv('project/dams_japan.csv')

In [14]:
df['Completed'].unique()

array(['1470', '1592', '1633', '1661', '1662', '1663', '1678', '1710',
       '1895', '1906', '1912', '1914', '1917', '1918', '1919', '1920',
       '1922', '1923', '1924', '1926', '1927', '1928', '1929', '1930',
       '1931', '1932', '1933', '1934', '1936', '1937', '1938', '1939',
       '1940', '1941', '1942', '1943', '1944', '1945', '1946', '1947',
       '1948', '1949', '1950', '1951', '1952', '1953', '1954', '1955',
       '1956', '1957', '1958', '1959', '1960', '1961', '1962', '1963',
       '1964', '1965', '1966', '1967', '1968', '1969', '1970', '1971',
       '1972', '1973', '1974', '1975', '1976', '1977', '1978', '1979',
       '1980', '1981', '1982', '1983', '1984', '1985', '1986', '1987',
       '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995',
       '1996', '1998', '1999', '2000', '2001', '2002', '2004', '2005',
       '2006', '2008', '2009', 'Incomplete?', '2003'], dtype=object)

In [15]:
df.drop(df[df.Completed=='Incomplete?'].index,inplace=True)

In [16]:
df['Completed'].unique()

array(['1470', '1592', '1633', '1661', '1662', '1663', '1678', '1710',
       '1895', '1906', '1912', '1914', '1917', '1918', '1919', '1920',
       '1922', '1923', '1924', '1926', '1927', '1928', '1929', '1930',
       '1931', '1932', '1933', '1934', '1936', '1937', '1938', '1939',
       '1940', '1941', '1942', '1943', '1944', '1945', '1946', '1947',
       '1948', '1949', '1950', '1951', '1952', '1953', '1954', '1955',
       '1956', '1957', '1958', '1959', '1960', '1961', '1962', '1963',
       '1964', '1965', '1966', '1967', '1968', '1969', '1970', '1971',
       '1972', '1973', '1974', '1975', '1976', '1977', '1978', '1979',
       '1980', '1981', '1982', '1983', '1984', '1985', '1986', '1987',
       '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995',
       '1996', '1998', '1999', '2000', '2001', '2002', '2004', '2005',
       '2006', '2008', '2009', '2003'], dtype=object)

In [17]:
df.to_csv('project/dams_japan.csv')

## Processing the Earthquake Data

In [36]:
df=pd.read_csv('project/earthquake_japan.csv')

## Splitting the Earthquake Data in 3 parts
```
    1. Between 2000 to 2005
    2. Between 2005 to 2009
    3. After 2009
```

### Between 2005 to 2009

In [19]:
df_5_to_9=pd.DataFrame(columns=['Latitude','Longitude','Date','Depth','Magnitude'])

In [20]:
from datetime import datetime as dt

In [21]:

row_list=list()
count=0
for index,row in df.iterrows():
    try:
        if dt.strptime('01/01/2005',"%m/%d/%Y")<=dt.strptime(row['Date'],"%m/%d/%Y")<=dt.strptime('12/31/2009',"%m/%d/%Y"):
            d={'Latitude':row['Latitude'],'Longitude':row['Longitude'],'Date':row['Date'],'Depth':row['Depth'],'Magnitude':row['Magnitude']}
            df_5_to_9.loc[count,:]=d
            count=count+1
            
    except Exception as e:
        print(e)

time data '1975-02-23T02:58:41.000Z' does not match format '%m/%d/%Y'
time data '2011-03-13T02:23:34.520Z' does not match format '%m/%d/%Y'

In [22]:
df_5_to_9.to_csv('project/earthquakes_2005_2009.csv')

### Before 2005

In [23]:
df_before_5=pd.DataFrame(columns=['Latitude','Longitude','Date','Depth','Magnitude'])

In [24]:
row_list=list()
count=0
for index,row in df.iterrows():
    try:
        if dt.strptime('01/01/2000',"%m/%d/%Y")<=dt.strptime(row['Date'],"%m/%d/%Y")<=dt.strptime('12/31/2005',"%m/%d/%Y"):
            d={'Latitude':row['Latitude'],'Longitude':row['Longitude'],'Date':row['Date'],'Depth':row['Depth'],'Magnitude':row['Magnitude']}
            df_before_5.loc[count,:]=d
            count=count+1
              
    except Exception as e:
        print(e)

time data '1975-02-23T02:58:41.000Z' does not match format '%m/%d/%Y'
time data '2011-03-13T02:23:34.520Z' does not match format '%m/%d/%Y'

In [25]:
df_before_5.to_csv('project/earthquakes_before_2005.csv')

### After 2009

In [37]:
df_after_9=pd.DataFrame(columns=['Latitude','Longitude','Date','Depth','Magnitude'])

In [38]:

row_list=list()
count=0
for index,row in df.iterrows():
    try:
        if dt.strptime('01/01/2010',"%m/%d/%Y")<=dt.strptime(row['Date'],"%m/%d/%Y"):
            d={'Latitude':row['Latitude'],'Longitude':row['Longitude'],'Date':row['Date'],'Depth':row['Depth'],'Magnitude':row['Magnitude']}
            df_after_9.loc[count,:]=d
            count=count+1
              
    except Exception as e:
        print(e)

time data '1975-02-23T02:58:41.000Z' does not match format '%m/%d/%Y'
time data '2011-03-13T02:23:34.520Z' does not match format '%m/%d/%Y'

In [39]:
df_after_9.to_csv('project/earthquakes_after_2009.csv')


## Dams between 2005 to 2009

In [30]:
df=pd.read_csv('project/dams_japan.csv')

In [31]:
df_dams_bw_05_to_09=pd.DataFrame(columns=['Country','Name','Completed','Latitude','Longitude'])

In [32]:
count =0
alist=list()
for index,row in df.iterrows():
    try:
        if row['Completed']>=2005 and row['Completed']<=2009:
            d={'Country':row['Country'],'Name':row['Name'],'Completed':row['Completed'],'Latitude':row['Latitude'],'Longitude':row['Longitude']}
            df_dams_bw_05_to_09.loc[count,:]=d
            count=count+1
    except Exception as e:
        print(e)

In [33]:
df_dams_bw_05_to_09.to_csv('project/dams_between_2005_to_2009.csv')

# Plotting the data

In [40]:
import folium
import pandas as pd

data = pd.read_csv('project/dams_between_2005_to_2009.csv')
lat = list(data["Latitude"])
lon = list(data["Longitude"])
names=list(data["Name"])
comp=list(data["Completed"])
    

map = folium.Map(location=[38.58, -99.09], zoom_start=6, tiles="Mapbox Bright")
fgv = folium.FeatureGroup(name="Dams b/w 2005 to 2009")

for lt, ln,name in zip(lat, lon,names):
    fgv.add_child(folium.Marker(
    location=[lt,ln],
    popup=str(name),
    icon=folium.Icon(color='green')
        ))
    
fgd=folium.FeatureGroup(name='Before 2005')

data1=pd.read_csv('project/earthquakes_before_2005.csv')
lat=list(data1['Latitude'])
lon=list(data1['Longitude'])
depth=list(data1['Depth'])
elev=list(data1['Magnitude'])

def color_producer(elevation):
    if elevation >6.00:
        return 'red'
    elif 5.8 <= elevation < 6.00:
        return 'blue'
    else:
        return 'white'

def radius_producer(dep):
    if dep > 60:
        return 8
    elif 50 <= dep <60:
        return 3
    else:
        return 2
    
for lt, ln, el,dep in zip(lat, lon, elev,depth):
    fgd.add_child(folium.CircleMarker(location=[lt, ln], radius = radius_producer(dep), popup=str(el),
    fill_color=color_producer(el), fill=True,  color = 'grey', fill_opacity=0.7))
    
    
fgd1=folium.FeatureGroup(name='Between 2005 to 2009')
data1=pd.read_csv('project/earthquakes_2005_2009.csv')
lat=list(data1['Latitude'])
lon=list(data1['Longitude'])
depth=list(data1['Depth'])
elev=list(data1['Magnitude'])

for lt, ln, el,dep in zip(lat, lon, elev,depth):
    fgd1.add_child(folium.CircleMarker(location=[lt, ln], radius = radius_producer(dep), popup=str(el),
    fill_color=color_producer(el), fill=True,  color = 'grey', fill_opacity=0.7))


fgd2=folium.FeatureGroup(name='After 2009')
data1=pd.read_csv('project/earthquakes_after_2009.csv')
lat=list(data1['Latitude'])
lon=list(data1['Longitude'])
depth=list(data1['Depth'])
elev=list(data1['Magnitude'])

for lt, ln, el,dep in zip(lat, lon, elev,depth):
    fgd2.add_child(folium.CircleMarker(location=[lt, ln], radius = radius_producer(dep), popup=str(el),
    fill_color=color_producer(el), fill=True,  color = 'grey', fill_opacity=0.7))

    
map.add_child(fgv)
map.add_child(fgd)
map.add_child(fgd1)
map.add_child(fgd2)
map.add_child(folium.LayerControl())
map.save('project/map_final_analysis.html')